Polymer
  is: 'nano-avatar'
  properties:
    ###*
    # name
    # Abcd -> A
    # Abcd Efg -> AE
    # Abcd E Fg -> AF
    ###
    name:
      type: String
      observer: '_nameChanged'
    ###*
    # The actual text in avatar. Generated by `name` or `email`.
    ###
    text:
      type: String
      observer: '_textChanged'

  _nameChanged: (name) ->
    # generate initials from name
    parts = name.split(' ').map (part) -> part[0].toUpperCase()
    if parts.length is 1
      @text = parts[0]
    else
      @text = parts.shift() + parts.pop()

  _textChanged: (text) ->
    # currently ripped from initial.js
    # TODO rewrite

    # TODO use the material design pallet colors

    colors = ["#1abc9c", "#16a085", "#f1c40f", "#f39c12", "#2ecc71", "#27ae60", "#e67e22", "#d35400", "#3498db", "#2980b9", "#e74c3c", "#c0392b", "#9b59b6", "#8e44ad", "#bdc3c7", "#34495e", "#2c3e50", "#95a5a6", "#7f8c8d", "#ec87bf", "#d870ad", "#f69785", "#9ba37e", "#b49255", "#b49255", "#a94136"]

    options =
      seed: 0,
      charCount: 1,
      height: 128,
      width: 128,
      fontSize: 64,
      fontWeight: 400,
      radius: 5

    textElement = document.createElementNS 'http://www.w3.org/2000/svg', 'text'
    textElement.innerHTML = @text
    textElement.setAttribute 'x', '50%'
    textElement.setAttribute 'y', '50%'
    textElement.setAttribute 'dy', '0.35em'
    textElement.setAttribute 'pointerEvents', 'auto'
    textElement.setAttribute 'fill', 'white'
    textElement.setAttribute 'textAnchor', 'middle'
    textElement.style.fontSize = '48px'

    svg = document.createElementNS 'http://www.w3.org/2000/svg', 'svg'
    svg.attributes =
      pointerEvents: 'none'
      width: 128
      height: 128
    svg.style =
      backgroundColor: colors[Math.floor(Math.random()*colors.length)]
      width: '128px'
      height: '128px'
      borderRadius: '5px'

    svg.appendChild textElement

    wrapper = document.createElement 'div'
    wrapper.appendChild svg.cloneNode true

    svgHTML = window.btoa unescape encodeURIComponent wrapper.outerHTML

    @$.wrapper.setAttribute 'src', ( 'data:image/svg+xml;base64,' + svgHTML )
